[package]
name = "logcat_tui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
num-traits = "0.2.14"
termion = "1.5"
tui = "0.15"
unicode-width = "0.1"
unicode-segmentation = "1.7"
