[package]
name = "logcat_tui"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
fps_counter = "2.0.0"
num-traits = "0.2.14"
termion = "1.5"
tui = "0.15"
unicode-width = "0.1"
unicode-segmentation = "1.7"
